### ISSUE TITLE
404. Ошибка сайта + орфография

### ISSUE THREAD

**Issue by vlalog** [wc1c/wc1c#1]
https://wc1c.info/changelog
1. Орфография ("ОшиПка)
2. Нет changelog-а

**Comment by vlalog** [comment]
и еще: репозиторий открыт к изменениям для всех, что может стать причиной вандализма

**Comment by Mofsy** [comment]
1. Так было задумано.
2. Он появится после первого публичного релиза. В данный момент сайт наполняется, и в списке изменений пока мало смысла.
