### ISSUE TITLE
Дополнение документации

### ISSUE THREAD

**Issue by vlalog** [wc1c/wc1c#2]
Добавьте, пожалуйста, в документацию расположение лог-файлов.
Спасибо!

**Comment by vlalog** [comment]
И, если можно, продублируйте сюда =)

**Comment by Mofsy** [comment]
На данный момент логирование описано в возможностях https://wc1c.info/features/logging
После релиза, данная информация будет доработана и отражена в документации.
Кроме этого, путь к файлам логов будет выведен где нибудь в панели управления. Если имеются четкое понимание где и в каком виде - примем информацию к сведению.

**Comment by vlalog** [comment]
Предлагаю в панели настроек, в описании под пунктом "Уровень логирования"

**Comment by vlalog** [comment]
![image](https://user-images.githubusercontent.com/56760680/82910463-56878980-9f73-11ea-9db3-3a70177e4cc5.png)

**Comment by Mofsy** [comment]
Принято, будет реализовано.

**Comment by vlalog** [comment]
Спасибо.
