### ISSUE TITLE
Не работает импорт

### ISSUE THREAD

**Issue by vlalog** [wc1c/wc1c#3]
К сожалению, столкнулся с проблемой: плагин не импортирует товары.
1с отображает успех, логи тоже.
```
200 -|- 2020-05-26T14:25:44+00:00 -|- INFO -|- file_import: start -|- 
200 -|- 2020-05-26T14:25:44+00:00 -|- INFO -|- file_import: type_file - import -|- 
200 -|- 2020-05-26T14:25:44+00:00 -|- INFO -|- file_import: catalog_processing start -|- 
200 -|- 2020-05-26T14:25:44+00:00 -|- INFO -|- parse_xml_catalog: catalog_guid b930b7f9-1d42-46fa-9c23-646156fb4ff9 -|- 
200 -|- 2020-05-26T14:25:44+00:00 -|- INFO -|- parse_xml_catalog: classifier_guid b930b7f9-1d42-46fa-9c23-646156fb4ff9 -|- 
200 -|- 2020-05-26T14:25:44+00:00 -|- INFO -|- parse_xml_catalog: catalog_name Каталог товаров B930B7F9 -|- 
200 -|- 2020-05-26T14:25:44+00:00 -|- INFO -|- file_import: catalog_processing end, success -|- 
200 -|- 2020-05-26T14:25:44+00:00 -|- INFO -|- file_import: end & true -|- 
200 -|- 2020-05-26T14:25:44+00:00 -|- INFO -|- api_catalog_mode_import: success -|- 
```

**Comment by vlalog** [comment]
<div class="wrap">

        
    
	
<div class="card col-24 mb-2 mt-2 pt-0 pb-0 pl-0 pr-0 border-0" style="border-radius: 0!important;">
    <div class="card-header p-2">
        <h5 class="m-0 p-0 pb-1">Окружение WC1C</h5>
    </div>
    <div class="card-body p-0">
        <table class="table  m-0 table-bordered">
            <tbody>
            
<tr class="">
    <td class="" style="width: 40%;">
	    Версия WC1C    </td>
    <td class="">
	    нет    </td>
</tr>
<tr class="">
    <td class="" style="width: 40%;">
	    Каталог загрузки    </td>
    <td class="">
	    /home/users/1/hidden    </td>
</tr>
<tr class="">
    <td class="" style="width: 40%;">
	    Количество расширений    </td>
    <td class="">
	    0    </td>
</tr>
<tr class="">
    <td class="" style="width: 40%;">
	    Количество схем    </td>
    <td class="">
	    1    </td>
</tr>
<tr class="">
    <td class="" style="width: 40%;">
	    Количество иструментов    </td>
    <td class="">
	    1    </td>
</tr>            </tbody>
        </table>
    </div>
</div>
<div class="card col-24 mb-2 mt-2 pt-0 pb-0 pl-0 pr-0 border-0" style="border-radius: 0!important;">
    <div class="card-header p-2">
        <h5 class="m-0 p-0 pb-1">Окружение WooCommerce</h5>
    </div>
    <div class="card-body p-0">
        <table class="table  m-0 table-bordered">
            <tbody>
            
<tr class="">
    <td class="" style="width: 40%;">
	    Версия WooCommerce    </td>
    <td class="">
	    4.0.1    </td>
</tr>
<tr class="">
    <td class="" style="width: 40%;">
	    Типы продуктов WooCommerce    </td>
    <td class="">
	    external, grouped, simple, variable    </td>
</tr>
<tr class="">
    <td class="" style="width: 40%;">
	    Валюта WooCommerce    </td>
    <td class="">
	    RUB    </td>
</tr>
<tr class="">
    <td class="" style="width: 40%;">
	    Символ валюты WooCommerce    </td>
    <td class="">
	    ₽    </td>
</tr>            </tbody>
        </table>
    </div>
</div>
<div class="card col-24 mb-2 mt-2 pt-0 pb-0 pl-0 pr-0 border-0" style="border-radius: 0!important;">
    <div class="card-header p-2">
        <h5 class="m-0 p-0 pb-1">Окружение WordPress</h5>
    </div>
    <div class="card-body p-0">
        <table class="table  m-0 table-bordered">
            <tbody>
            
<tr class="">
    <td class="" style="width: 40%;">
	    Домашний адрес    </td>
    <td class="">
	   hidden    </td>
</tr>
<tr class="">
    <td class="" style="width: 40%;">
	    Адрес сайта    </td>
    <td class="">
	    hidden</td>
</tr>
<tr class="">
    <td class="" style="width: 40%;">
	    Версия WordPress    </td>
    <td class="">
	    5.4.1    </td>
</tr>
<tr class="">
    <td class="" style="width: 40%;">
	    WordPress мультисайт    </td>
    <td class="">
	    нет    </td>
</tr>
<tr class="">
    <td class="" style="width: 40%;">
	    Отладка WordPress    </td>
    <td class="">
	    нет    </td>
</tr>
<tr class="">
    <td class="" style="width: 40%;">
	    WordPress cron    </td>
    <td class="">
	    да    </td>
</tr>
<tr class="">
    <td class="" style="width: 40%;">
	    Лимит памяти WordPress    </td>
    <td class="">
	    40M    </td>
</tr>            </tbody>
        </table>
    </div>
</div>
<div class="card col-24 mb-2 mt-2 pt-0 pb-0 pl-0 pr-0 border-0" style="border-radius: 0!important;">
    <div class="card-header p-2">
        <h5 class="m-0 p-0 pb-1">Окружение сервера</h5>
    </div>
    <div class="card-body p-0">
        <table class="table  m-0 table-bordered">
            <tbody>
            
<tr class="">
    <td class="" style="width: 40%;">
	    Информация сервера    </td>
    <td class="">
	    Apache    </td>
</tr>
<tr class="">
    <td class="" style="width: 40%;">
	    Версия PHP    </td>
    <td class="">
	    7.4.0    </td>
</tr>
<tr class="">
    <td class="" style="width: 40%;">
	    Версия СУБД    </td>
    <td class="">
	    5.5.5    </td>
</tr>
<tr class="">
    <td class="" style="width: 40%;">
	    Сухосин    </td>
    <td class="">
	    нет    </td>
</tr>
<tr class="">
    <td class="" style="width: 40%;">
	    Fsockopen or curl enabled    </td>
    <td class="">
	    да    </td>
</tr>
<tr class="">
    <td class="" style="width: 40%;">
	    CURL info    </td>
    <td class="">
	    7.47.2, OpenSSL/1.0.1e    </td>
</tr>
<tr class="">
    <td class="" style="width: 40%;">
	    Временная зона    </td>
    <td class="">
	    UTC    </td>
</tr>
<tr class="">
    <td class="" style="width: 40%;">
	    PHP post max size (максимальный размер POST-запроса)    </td>
    <td class="">
	    2G    </td>
</tr>
<tr class="">
    <td class="" style="width: 40%;">
	    PHP max execution time    </td>
    <td class="">
	    900000999999999999090900s    </td>
</tr>
<tr class="">
    <td class="" style="width: 40%;">
	    PHP max input vars    </td>
    <td class="">
	    1000    </td>
</tr>
<tr class="">
    <td class="" style="width: 40%;">
	    PHP max upload size    </td>
    <td class="">
	    2147483648    </td>
</tr>
<tr class="">
    <td class="" style="width: 40%;">
	    PHP soapclient enabled    </td>
    <td class="">
	    да    </td>
</tr>
<tr class="">
    <td class="" style="width: 40%;">
	    PHP domdocument enabled    </td>
    <td class="">
	    да    </td>
</tr>
<tr class="">
    <td class="" style="width: 40%;">
	    PHP gzip enabled    </td>
    <td class="">
	    да    </td>
</tr>
<tr class="">
    <td class="" style="width: 40%;">
	    PHP mbstring enabled    </td>
    <td class="">
	    да    </td>
</tr>            </tbody>
        </table>
    </div>
</div>
	
</div>

**Comment by Mofsy** [comment]
Все очень просто. Релиза еще не было.
Механизм обработки данных еще не внедрен в схему по умолчанию :)

До конца недели скорее всего будет сделано.

**Comment by vlalog** [comment]
Принято, спасибо 👍 :)
